### ISSUE TITLE
Any discord support server?

### ISSUE THREAD

**Issue by yinrozvel** [InflatibleYoshi/discord-samwise#4]
Saw this on top.gg but it seems the bot is offline. Any way to know when will the bot is coming back and is there a discord support server to keep up with updates?

**Comment by InflatibleYoshi** [comment]
Hello, I don't have a support server for updates, I ignored this project for a few months but I did some work this morning to get it up and running again. I probably won't set up a support server unless I get bombarded with messages via DMs through top.gg
